# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragonpayPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=40)),
                ('user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('processor_id', models.CharField(blank=True, max_length=8, null=True)),
                ('processor_detail', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(max_length=128)),
                ('currency', models.CharField(default=b'PHP', max_length=3)),
                ('status', models.CharField(choices=[(b'S', b'Success'), (b'F', b'Failed'), (b'P', b'Pending'), (b'G', b'In progress'), (b'V', b'Voided')], default=b'P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DragonpayPayoutUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('birthdate', models.DateField()),
                ('mobile', models.CharField(max_length=24)),
                ('address1', models.CharField(max_length=32)),
                ('address2', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('zip', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DragonpayTransaction',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default=b'PHP', max_length=3)),
                ('description', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=40)),
                ('param1', models.CharField(blank=True, max_length=80, null=True)),
                ('param2', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[(b'S', b'Success'), (b'F', b'Failed'), (b'P', b'Pending'), (b'U', b'Unknown'), (b'R', b'Refund'), (b'K', b'Chargeback'), (b'V', b'Voided'), (b'A', b'Authorized')], default=b'P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
