# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dragonpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonpaypayout',
            name='processor_id',
            field=models.CharField(blank=True, choices=[(b'BDO', b'Banco De Oro'), (b'BPI', b'Bank of the Philippine Islands'), (b'CBC', b'Chinabank'), (b'EWB', b'East West Bank'), (b'LBP', b'Land Bank of the Philippines'), (b'MBTC', b'Metrobank'), (b'PNB', b'Philippine National Bank'), (b'RCBC', b'RCBC'), (b'SBC', b'Security Bank'), (b'UBP', b'Union Bank'), (b'UCPB', b'UCPB'), (b'PSB', b'PS Bank'), (b'CEBL', b'Cebuana Lhuilier'), (b'GCSH', b'GCash'), (b'SMRT', b'Smart Money')], max_length=8, null=True),
        ),
    ]
