# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dragonpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragonpaytransaction',
            name='refno',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
