# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dragonpay', '0003_larger_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragonpayLifetimeUser',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name=b'LifetimeUser ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
